name: lime_nlp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pytorch
  - numpy
  - pandas
  - scikit-learn
  - transformers
  - wandb
  - pydantic
  - nltk
  - python-dotenv
  - langchain
  - tiktoken
  - openai
  - anthropic
  - tqdm
  - evaluate
  - scikit-learn
  - sentence-transformers
  - jupyterlab
  - shap
  - captum
  - pip
  - pip:
      - -e .
